# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Build
        run: go build -o repositorio-test -v

      - name: Start Service
        run: sudo systemctl start repositorio-test
